[workspace]
preview = ["pixi-build"]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "mojot"
description = "Mojo GDExtension."
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"
license = "MIT"

[tasks]
build = "mojo build --emit shared-lib -o example/bin/mojot.so src/init.mojo"
test = { cmd = "godot -e --path example", depends-on = "build" }

[dependencies]
mojo = ">=0.26.1.0.dev2026012105,<0.27"
